version: '3'

services:
  lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
      - libraries_cache:/usr/local/lib/R/site-library
    env_file:
      - .env/jupyter
    # command: ["jupyter", "notebook", "--notebook-dir=/usr/src/app/lab_app", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]

volumes:
  libraries_cache:
